version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'resolver'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - cadc-target-resolver.cadc.dao.nrc.ca
  cadc-target-resolver.cadc.dao.nrc.ca:
    image: opencadc/cadc-target-resolver:SNAPSHOT
    networks:
      - 'resolver'
    environment:
      CATALINA_OPTS: -Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca

# Create the network 'resolver' for which this system will run within.
networks:
  resolver:
