version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'resolver'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './root:/usr/share/nginx/html'
    depends_on:
      - resolver
  resolver:
    image: opencadc/cadc-target-resolver:SNAPSHOT
    networks:
      - 'resolver'

# Create the network 'resolver' for which this system will run within.
networks:
  resolver:
