name: Java/Docker CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: gradle -i clean build test
      - name: Build the Docker image
        run: mkdir docker && cp Dockerfile docker/ && cp build/libs/*.war docker/ && docker build -t opencadc/cadc-target-resolver:SNAPSHOT -f docker/Dockerfile docker/
      - name: Prepare for Integration Test
        run: docker-compose -f integrationTest/docker-compose.yml up -d && docker ps -a && docker-compose -f integrationTest/docker-compose.yml logs resolver && docker-compose -f integrationTest/docker-compose.yml logs proxy
      - name: Execute Integration Tests
        run: curl -vL -d 'level=DEBUG' http://localhost/cadc-target-resolver/logControl && curl -Lv http://localhost/capabilities-http.xml && gradle -i -Dca.nrc.cadc.reg.client.RegistryClient.host=localhost clean intTest
        env:
          RESOURCE_CAPS_URL: http://localhost/reg/resource-caps
